ENVIRONMENT: local
PORT: 3004
LOG_LEVEL: info
SERVICE_NAME: wallet
MONITORING_PORT: 8889

KMS_KEY_ID: 
AWS_ENDPOINT: http://localhost:4566
AWS_REGION: us-east-2

GRPC_PORT: 9005

BIP32_SEED:

MOCK_ENCLAVE: true
MOCK_SEED: '0x0e7a1697d3a906dc7cd490b6854360dd6af3f9dd0f0908f510c407bd0811a7b0'

