{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "test-instance.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-instance.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "test-instance.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    path: {{ .Values.serviceMonitor.path | quote }}
{{- end }}