replicaCount: 9
image:
  repository: dimozone/synthetic-wallet-instance
  pullPolicy: IfNotPresent
  tag: 0.3.3
cronJob:
  enabled: false
env: {}
ingress:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
