replicaCount: 1

web:
  image:
    tag: 17261ec

enclave:
  image:
    tag: 30ba023

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/limit-rps: '3'
    external-dns.alpha.kubernetes.io/hostname: synthetic-wallet-instance.dimo.zone
  hosts:
    - host: synthetic-wallet-instance.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

