apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetic-wallet-instance.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-wallet-instance.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/webconfig: {{ include (print $.Template.BasePath "/webenvconfigmap.yaml") . | sha256sum }}
        checksum/enclaveconfig: {{ include (print $.Template.BasePath "/enclaveenvconfigmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synthetic-wallet-instance.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers: []
      containers:
        - name: synthetic-wallet-instance
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-config
          - secretRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-secret
          ports:
{{ toYaml .Values.web.ports | indent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: mon-http
          readinessProbe:
            httpGet:
              path: /
              port: mon-http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
        - name: synthetic-wallet-enclave
          securityContext:
            {{- toYaml .Values.enclave.securityContext | nindent 12 }}
          image: "{{ .Values.enclave.image.repository }}:{{ .Values.enclave.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.enclave.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-enclave-config
          - secretRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-secret
          livenessProbe:
            exec:
              command:
                - /run.sh
                - 'healthcheck'
            failureThreshold: 2
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.enclave.resources | nindent 12 }}
          volumeMounts:
            - name: nitro-enclaves
              mountPath: /dev/nitro_enclaves
            - name: hugepage-1gi
              mountPath: /dev/hugepages
              readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: nitro-enclaves
        hostPath:
          path: /dev/nitro_enclaves
      - name: hugepage-1gi
        emptyDir:
          medium: HugePages-1Gi
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
