apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetic-wallet-instance.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-wallet-instance.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/envconfigmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "synthetic-wallet-instance.selectorLabels" . | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synthetic-wallet-instance.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers: []
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-config
          - secretRef:
              name: {{ include "synthetic-wallet-instance.fullname" . }}-secret
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: mon-http
          readinessProbe:
            httpGet:
              path: /
              port: mon-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: synthetic-wallet-enclave
          image: dimozone/synthetic-wallet-enclave:d5b0d6f
          env:
          - name: ENCLAVE_CPU_COUNT
            value: '2'
          - name: ENCLAVE_MEMORY_SIZE
            value: '1000'
          - name: ENCLAVE_CID
            value: '16'
          - name: AWS_REGION
            value: 'us-east-2'
          livenessProbe:
            exec:
              command:
                - /run.sh
                - 'healthcheck'
            failureThreshold: 2
            initialDelaySeconds: 10
          resources:
            limits:
              aws.ec2.nitro/nitro_enclaves: "1"
              hugepages-1Gi: 1Gi
              memory: 512Mi
              cpu: 500m
            requests:
              aws.ec2.nitro/nitro_enclaves: "1"
              hugepages-1Gi: 1Gi
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: nitro-enclaves
              mountPath: /dev/nitro_enclaves
            - name: hugepage-1gi
              mountPath: /dev/hugepages
              readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: nitro-enclaves
        hostPath:
          path: /dev/nitro_enclaves
      - name: hugepage-1gi
        emptyDir:
          medium: HugePages-1Gi
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
